---
- name: destroy vms
  hosts: vm_hosts
  vars_files: vars/main.yml
  tasks:
    - name: set home fact
      ansible.builtin.set_fact:
        home_dir: "{{ ansible_env.HOME }}"

    - name: Destroy server VM
      community.general.terraform:
        force_init: true
        project_path: "{{ workspace_directory.base_path }}/clusters/{{ cluster_name }}/{{ item }}"
        state: absent
      loop:
        - servers
      when: "'server_hosts' in group_names"
      become: true

    - name: Destroy agent VM
      community.general.terraform:
        force_init: true
        project_path: "{{ workspace_directory.base_path }}/clusters/{{ cluster_name }}/{{ item }}"
        state: absent
      loop:
        - agents
      when: "'agent_hosts' in group_names"
      become: true
