---
# tasks file for rke2_node
- ansible.builtin.include_tasks: 00_network_manager.yml
- ansible.builtin.include_tasks: 01_install_rke2.yml
- name: configure rke2 agent
  when: "rke2_node_type == 'agent'"
  ansible.builtin.include_tasks:
    file: 02_configure_rke2_agent.yml
- ansible.builtin.include_tasks: 03_start_rke2.yml
- name: get rke2 server data
  when: "rke2_node_type == 'server'"
  ansible.builtin.include_tasks:
    file: 04_get_rke2_server_data.yml
