---
# tasks file for rke2_node

- name: Wait 600 seconds for target connection to become reachable/usable
  ansible.builtin.wait_for_connection:
    timeout: 600
    delay: 0

- name: Ping host to check status
  ansible.builtin.ping:

- name: Extract facts from setup
  ansible.builtin.setup:
  register: machine_facts

- name: Set relevant facts for the host
  ansible.builtin.set_fact:
    host_ip: "{{ machine_facts.ansible_facts.ansible_default_ipv4.address }}"
    host_interface: "{{ machine_facts.ansible_facts.ansible_default_ipv4.interface }}"
    host_mac: "{{ machine_facts.ansible_facts.ansible_default_ipv4.macaddress }}"
    host_fqdn: "{{ machine_facts.ansible_facts.ansible_fqdn }}"


- ansible.builtin.include_tasks: 00_network_manager.yml
- ansible.builtin.include_tasks: 01_install_rke2.yml
- name: configure rke2 agent
  when: "rke2_node_type == 'agent'"
  ansible.builtin.include_tasks:
    file: 02_configure_rke2_agent.yml
- ansible.builtin.include_tasks: 03_start_rke2.yml
- name: get rke2 server data
  when: "rke2_node_type == 'server'"
  ansible.builtin.include_tasks:
    file: 04_get_rke2_server_data.yml
